export const SET_CUSTOMER = 'SET_CUSTOMER'
export const NEWSLETTER_SUBSCRIBE = 'NEWSLETTER_SUBSCRIBE'
export const NEWSLETTER_UNSUBSCRIBE = 'NEWSLETTER_UNSUBSCRIBE'
export const SET_SAVED_AS_GUEST = 'SAVED_AS_GUEST'